name: Update Dam Storage Rates

on:
  schedule:
    - cron: '2 * * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Python環境のセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 依存ライブラリのインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 川の防災情報スクレイピング実行
        env:
          GAS_WEBHOOK_URL: ${{ secrets.GAS_WEBHOOK_URL }}
        #run: python scraper.py

      - name: 大島ダムスクレイピング実行
        env:
          GAS_WEBHOOK_URL: ${{ secrets.GAS_WEBHOOK_URL }}
        #run: python scraper_oshima.py
        
      - name: 千葉県の水道用ダムスクレイピング実行
        env:
          GAS_WEBHOOK_URL: ${{ secrets.GAS_WEBHOOK_URL }}
        run: python scraper_chiba.py
